// web/components/pwa.tsx
"use client";

import { type ReactElement, useEffect } from "react";
import "../utils/install";

export default function Pwa(): ReactElement | null {
  useEffect(() => {
    if (!("serviceWorker" in navigator)) return;
    // Never in dev: `next dev` serves modules a cache would hand back stale,
    // with no version bump between edits to invalidate them. The file is built
    // there anyway, so flipping this line is all it takes to try it locally.
    if (process.env.NODE_ENV !== "production") return;
    const base = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
    // Deliberately after load. Registration competes with the first paint's own
    // requests for the same connection, and the worker is of no use on the visit
    // that installs it.
    const start = () => {
      navigator.serviceWorker
        .register(`${base}/sw.js`, { scope: `${base}/` })
        .catch((error) => console.warn("service worker", error));
    };
    if (document.readyState === "complete") start();
    else window.addEventListener("load", start, { once: true });
  }, []);
  return null;
}

// web/src/lib/components/pwa.svelte
<script lang="ts">
  import { BASE_PATH } from "../base";
  import { startInstall } from "../install.svelte";

  // Renders nothing: registers the service worker and asks the browser whether
  // kip can be installed.
  $effect(() => {
    startInstall();
    if (!("serviceWorker" in navigator)) return;
    // Never in dev: the dev server serves modules a cache would hand back stale,
    // with no version bump between edits to invalidate them. The file is built
    // there anyway, so flipping this line is all it takes to try it locally.
    if (import.meta.env.DEV) return;
    // Deliberately after load. Registration competes with the first paint's own
    // requests for the same connection, and the worker is of no use on the visit
    // that installs it.
    const start = (): void => {
      navigator.serviceWorker
        .register(`${BASE_PATH}/sw.js`, { scope: `${BASE_PATH}/` })
        .catch((error) => console.warn("service worker", error));
    };
    if (document.readyState === "complete") start();
    else window.addEventListener("load", start, { once: true });
  });
</script>
